### ISSUE TITLE
use `Normal` instead of `Ignore` for arguments

### ISSUE THREAD

**Issue by ModProg** [nastevens/vim-duckscript#2]
I seems that `Ignore` is sometimes mapped to the background color which is a bit hard to read ;).

e.g. `blue` has this problem:
![grafik](https://user-images.githubusercontent.com/11978847/155669275-bebc7ae6-88b2-4187-accb-78668e5867c1.png)

I would suggest changing this to link to e.g. `Normal` instead
https://github.com/nastevens/vim-duckscript/blob/047e939043e1d18c68e171862c2996648491e381/syntax/duckscript.vim#L90

**Comment by nastevens** [comment]
One of those things where I wrote the code and now looking back at it go "what in the world was I thinking?" :smile:

Thanks for pointing this out!
